### ISSUE TITLE
Press key 2 with Shift simultaneously give [ and not @

### ISSUE THREAD

**Issue by v-s-p** [TNKSoftware/ergomax_tnk#1]
Tanaka-san, your firmware is truly impressive. However, as a novice in keyboard flashing, I find myself in need of some explanations. While attempting to remap certain keys, I encountered an unexpected issue. When I pressed the "2" key with the "Shift" key simultaneously, instead of getting the "@" symbol as expected, it produced "[". I'm puzzled as to what might be causing this problem. Could you kindly shed some light on the issue?

**Comment by TNKSoftware** [comment]
I'm sorry for the late reply.

The reason why key inputs respond unexpectedly is because the keyboard behaves as a Japanese layout.

" is defined, so please delete [#include "keymap_japanese.h"] in "keymap.c" and rewrite the definition for Japanese keyboards such as "JP_ZKHK" in the keymaps[][MATRIX_ROWS][MATRIX_COLS] array.

**Comment by v-s-p** [comment]
O...i see...my bad x) Thank you so much!
